# Generated by Django 3.1.7 on 2021-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.SmallIntegerField()),
                ('industry', models.CharField(max_length=40)),
                ('career', models.CharField(max_length=40)),
                ('short_bio', models.CharField(max_length=100)),
                ('long_bio', models.CharField(max_length=1000)),
                ('profile_image', models.ImageField(height_field=200, upload_to='', width_field=200)),
                ('merit_points', models.SmallIntegerField()),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
